"""Predicts typical daily calorie intake from body measurements.

Wraps the RandomForestRegressor trained by scripts/train_models.py on NHANES
2017-2018 (US CDC / NCHS, public domain; 4,624 adults).

WHAT THIS PREDICTS, AND WHAT IT DOES NOT
----------------------------------------
This is a *descriptive* model: it answers "how much do people with this age,
sex and body composition typically eat", learned from measured 24-hour dietary
recalls. It is not a recommendation, and it is not a calorie requirement.
``calculations.calculate_daily_calorie_target`` remains the prescriptive number
the app plans meals against; this sits beside it as a reference point.

WHY IT EARNS ITS PLACE
----------------------
On a held-out test set it beats the Mifflin-St Jeor formula the app already
uses, on both metrics:

    model              MAE (kcal)     R2
    mean baseline           684.4   -0.001
    Mifflin-St Jeor         650.6    0.071
    RandomForest            632.9    0.130

Those figures are regenerated by scripts/train_models.py and written to
models/model_metrics.json, so they can be re-checked rather than taken on trust.

R2 of 0.130 is genuinely low, and the module does not pretend otherwise. A
single day's dietary recall is a noisy measure of habitual intake - the test
set's own standard deviation is about 855 kcal - so most of that variation is
not predictable from body measurements by any model. The honest claim is
narrow: it is modestly better than the standard formula at this task.
"""

import json
from pathlib import Path

import joblib
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
MODELS_DIR = ROOT / "models"

# Must match FEATURES in scripts/train_models.py, in the same order.
FEATURE_COLUMNS = ["age_years", "SEX_MALE", "height_cm", "weight_kg", "bmi"]


class CaloriePredictor:
    """Loads the trained model, or degrades gracefully if it is missing.

    Construction never raises. The app checks ``is_available`` and simply omits
    the reference figure when the artifact cannot be loaded, rather than failing
    to start over an optional feature.
    """

    def __init__(self, models_dir: Path = MODELS_DIR):
        self._model = None
        self._metrics = None
        self._load_error = None

        try:
            self._model = joblib.load(models_dir / "calorie_intake_rf.pkl")
        except (FileNotFoundError, OSError, EOFError) as exc:
            self._load_error = str(exc)
            return

        try:
            self._metrics = json.loads(
                (models_dir / "model_metrics.json").read_text(encoding="utf-8")
            )
        except (FileNotFoundError, OSError, ValueError):
            # Metrics are for display only; a usable model without them is fine.
            self._metrics = None

    @property
    def is_available(self) -> bool:
        return self._model is not None

    @property
    def metrics(self) -> dict | None:
        """Held-out test metrics recorded at training time, if available."""
        return self._metrics

    def predict(
        self,
        age_years: int,
        is_male: bool,
        height_cm: float,
        weight_kg: float,
        bmi: float,
    ) -> float:
        """Typical daily calorie intake, in kcal, for this profile.

        Raises:
            RuntimeError: If the model could not be loaded.
            ValueError: If any measurement is not positive.
        """
        if not self.is_available:
            raise RuntimeError(f"Calorie model unavailable: {self._load_error}")

        if min(age_years, height_cm, weight_kg, bmi) <= 0:
            raise ValueError("age, height, weight and BMI must all be positive")

        features = pd.DataFrame(
            [[age_years, int(is_male), height_cm, weight_kg, bmi]],
            columns=FEATURE_COLUMNS,
        )
        return round(float(self._model.predict(features)[0]), 0)
